services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Override defaults for Docker environment
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=  # Empty for local Redis (no auth needed)
      - REDIS_PASSWORD=  # Empty for local Redis (no auth needed)
      - HTTP_PORT=8080
      - CACHE_TTL_SCHEDULE=21600  # 6 hour cache TTL
      - CACHE_READABLE_KEYS=true  # Enable readable cache keys for debugging
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python main.py
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  pgdata:
  mongodata:
